name: 'Array Filter Action'
description: 'Filters a JSON array of strings created by another action'
author: 'David Brunow <david@shep.dog>'
branding:
  icon: 'settings'
  color: 'purple'
inputs:
  arrayToFilter:
    description: 'the JSON array of strings that you want filtered'
    required: true
  suffixFilter:
    description: 'the suffix string that you want to filter by'
    default: 'none'
    required: false
outputs:
  filteredArray:
    description: 'the input array filtered by provided filters'
runs:
  using: 'node12'
  main: 'dist/index.js'
